---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - forge.build
  resources:
  - builds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.forge.build
  resources:
  - gcpbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.forge.build
  resources:
  - gcpbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.forge.build
  resources:
  - gcpbuilds/status
  verbs:
  - get
  - patch
  - update
